const demonData = [
  { type: 'section', title: 'MAIN LIST', id: 'main-list' },
  { type: 'entry', level: 'Bloodlust', id: '42584142', video: 'https://youtu.be/7yoNKFHz-Wk', verifier: 'xbow', records: '' },
  { type: 'entry', level: 'Congregation', id: '68668045', video: 'https://youtu.be/2m2Vn3gAzSY', verifier: 'xbow', records: '' },
  { type: 'entry', level: 'Wasureta', id: '64658786', video: 'https://youtu.be/MuHJgxOGqmE', verifier: 'xbow', records: '' },
  { type: 'entry', level: 'Ouroboros', id: '56703691', video: 'https://youtu.be/z8ka3go-Bi8', verifier: 'njec', records: '' },
  { type: 'entry', level: 'Arctic Lights', id: '52919433', video: 'https://youtu.be/zg7UDY9WjCY', verifier: 'arctic', records: 'woolfys (100%)' },
  { type: 'entry', level: 'MISFIRE', id: '88244926', video: 'https://youtu.be/sSIMvQD7ip4', verifier: 'woolfys', records: '' },
  { type: 'entry', level: 'Idols', id: '10565740', video: 'https://youtu.be/sfhA7L6PVlc', verifier: 'njec', records: '' },
  { type: 'entry', level: 'moment', id: '68848817', video: 'https://youtu.be/BkM0V1QrejI', verifier: 'arctic', records: 'V01D (100%)' },
  { type: 'entry', level: 'Down Bass', id: '8147005', video: 'https://youtu.be/1APIOIDWqJc', verifier: 'xbow', records: 'arctic (100%)'},
  { type: 'entry', level: 'Silentium Gradas', id: '45626173', video: 'https://youtu.be/oEoEuPHRgoo', verifier: 'arctic', records: '' },
  { type: 'entry', level: 'Conical Depression', id: '17711004', video: 'https://youtu.be/vZqz7WF6GhI', verifier: 'arctic', records: '' },
  { type: 'entry', level: 'Sakupen Hell', id: '23262780', video: 'https://youtu.be/hUqVNOj-ibk', verifier: 'arctic', records: 'xbow (100%)' },
  { type: 'entry', level: 'Bloodbath', id: '10565740', video: 'https://youtu.be/nmblrKa3KI0', verifier: 'V01D', records: 'xbow (100%), woolfys (100%)' },
  { type: 'entry', level: 'Prismatic Haze', id: '59899374', video: 'https://youtu.be/wNh5cb7t7oA', verifier: 'njec', records: '' },
  { type: 'entry', level: 'Heartbeat', id: '20321297', video: 'https://youtu.be/ZEo_Oo8lJOI', verifier: 'arctic', records: '' },
  { type: 'entry', level: 'Maybe Possibly Thing', id: '60284098', video: 'https://youtu.be/90tdUusR1z0', verifier: 'arctic', records: '' },
  { type: 'entry', level: 'Totem', id: '83570278', video: 'https://youtu.be/01XT-L7iKUY', verifier: 'njec', records: '' },
  { type: 'entry', level: 'Cat Planet', id: '84766628', video: 'https://youtu.be/TSBEZZrFwZo', verifier: 'V01D', records: '' },
  { type: 'entry', level: 'MELTDOWN', id: '52527538', video: 'https://youtu.be/bu5b9xQv5s8', verifier: 'V01D', records: '' },
  { type: 'entry', level: 'Cataclysm', id: '3979721', video: 'https://youtu.be/J90L73YOR3k', verifier: 'arctic', records: 'V01D (100%), xbow (100%)' },
  { type: 'entry', level: 'Mizureta', id: '95764848', video: 'https://youtu.be/TENF98yxUnc', verifier: 'V01D', records: '' },
  { type: 'entry', level: 'Niwa', id: '87425029', video: 'https://youtu.be/9go3A0YHFII', verifier: 'V01D', records: '' },
  { type: 'entry', level: 'Without U', id: '119259720', video: 'https://youtu.be/GR-itf1xUsI', verifier: 'V01D', records: '' },
  { type: 'entry', level: 'The Ultimate Phase', id: '7174110', video: 'https://youtu.be/HWHW_v8ujwU', verifier: 'arctic', records: '' },
  { type: 'entry', level: 'Acu', id: '61079355', video: 'https://youtu.be/HGyNA3L46is', verifier: 'V01D', records: 'arctic (100%), xbow (100%)' },
  { type: 'entry', level: 'troll level', id: '76196489', video: 'https://youtu.be/MkDnz_Zx0_U', verifier: 'V01D', records: '' },
  { type: 'entry', level: 'Red World', id: '2374518', video: 'https://youtu.be/AlKpZB_ZH5s', verifier: 'V01D', records: 'xbow (100%)' },
  { type: 'section', title: 'LEGACY LIST', id: 'legacy-list' },
  { type: 'entry', level: 'Gunslinga Corridor', id: '58069223', video: 'https://youtu.be/Ale8EVqywiY', verifier: 'arctic', records: '' },
  { type: 'entry', level: 'Ice Carbon Diablo X', id: '814678', video: 'https://youtu.be/V0TbT8vriRg', verifier: 'V01D', records: 'xbow (100%)' }
];

window.demonData = demonData;