const demonData = [
  { type: 'section', title: 'MAIN LIST (extreme demons)', id: 'main-list' },
  { type: 'entry', level: 'Bloodlust', id: '42584142', youtube: 'https://youtu.be/7yoNKFHz-Wk', verifier: 'xbow', records: '' },
  { type: 'entry', level: 'Congregation', id: '68668045', youtube: 'https://youtu.be/2m2Vn3gAzSY', verifier: 'xbow', records: '' },
  { type: 'entry', level: 'Wasureta', id: '64658786', youtube: 'https://youtu.be/MuHJgxOGqmE', verifier: 'xbow', records: '' },
  { type: 'entry', level: 'Ouroboros', id: '56703691', youtube: 'https://youtu.be/z8ka3go-Bi8', verifier: 'njec', records: '' },
  { type: 'entry', level: 'Arctic Lights', id: '52919433', youtube: 'https://youtu.be/7oAd-3KSPH0', verifier: 'arctic', records: 'woolfys (100%)' },
  { type: 'entry', level: 'MISFIRE', id: '88244926', youtube: 'https://youtu.be/iWgNXgFMrfA', verifier: 'woolfys', records: '' },
  { type: 'entry', level: 'moment', id: '68848817', youtube: 'https://youtu.be/OcnjfzdMVgM', verifier: 'arctic', records: 'V01D (100%)' },
  { type: 'entry', level: 'Silentium Gradas', id: '45626173', youtube: 'https://youtu.be/oEoEuPHRgoo', verifier: 'arctic', records: '' },
  { type: 'entry', level: 'Conical Depression', id: '17711004', youtube: 'https://youtu.be/vZqz7WF6GhI', verifier: 'arctic', records: '' },
  { type: 'entry', level: 'Sakupen Hell', id: '23262780', youtube: 'https://youtu.be/8kHvyRqQzJA', verifier: 'arctic', records: 'xbow (100%)' },
  { type: 'entry', level: 'Bloodbath', id: '10565740', youtube: 'https://youtu.be/nmblrKa3KI0', verifier: 'V01D', records: 'xbow (100%), woolfys (100%)' },
  { type: 'entry', level: 'Cat Planet', id: '84766628', youtube: 'https://youtu.be/TSBEZZrFwZo', verifier: 'V01D', records: '' },
  { type: 'entry', level: 'MELTDOWN', id: '52527538', youtube: 'https://youtu.be/bu5b9xQv5s8', verifier: 'V01D', records: '' },
  { type: 'entry', level: 'Cataclysm', id: '3979721', youtube: 'https://youtu.be/J90L73YOR3k', verifier: 'arctic', records: 'V01D (100%), xbow (100%)' },
  { type: 'entry', level: 'Mizureta', id: '95764848', youtube: 'https://youtu.be/TENF98yxUnc', verifier: 'V01D', records: '' },
  { type: 'entry', level: 'Niwa', id: '87425029', youtube: 'https://youtu.be/9go3A0YHFII', verifier: 'V01D', records: '' },
  { type: 'entry', level: 'Without U', id: '119259720', youtube: 'https://youtu.be/GR-itf1xUsI', verifier: 'V01D', records: '' },
  { type: 'entry', level: 'Acu', id: '61079355', youtube: 'https://youtu.be/HGyNA3L46is', verifier: 'V01D', records: 'arctic (100%), xbow (100%)' },
  { type: 'entry', level: 'troll level', id: '76196489', youtube: 'https://youtu.be/MkDnz_Zx0_U', verifier: 'V01D', records: '' },
  { type: 'entry', level: 'Red World', id: '2374518', youtube: 'https://youtu.be/AlKpZB_ZH5s', verifier: 'V01D', records: 'xbow (100%)' },
  { type: 'section', title: 'LEGACY LIST (levels that were previously extreme demon but were changed to insane for whatever reason)', id: 'legacy-list' },
  { type: 'entry', level: 'Gunslinga Corridor', id: '58069223', youtube: 'https://youtu.be/Ale8EVqywiY', verifier: 'arctic', records: '' },
  { type: 'entry', level: 'Ice Carbon Diablo X', id: '814678', youtube: 'https://youtu.be/V0TbT8vriRg', verifier: 'V01D', records: 'xbow (100%)' }
];
